# Generated by Django 3.0.5 on 2020-09-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('product_type', models.CharField(default='', max_length=70)),
                ('water_line_compatible', models.BooleanField(default=False)),
                ('size', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('product_type', models.CharField(default='', max_length=70)),
                ('pack_size', models.IntegerField()),
                ('coffee_flavor', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
